import {requireAdmin,safeError} from "@/lib/adminAuth";import{supabaseJson}from"@/lib/supabaseAuth";
export const runtime="nodejs";
const reports:Record<string,{path:string,headers:string[],row:(x:any)=>unknown[]}>={
  affiliates:{path:"/rest/v1/affiliate_profiles?select=id,partner_type,status,affiliate_code,coupon_code,created_at,approved_at,profiles!affiliate_profiles_user_id_fkey(email,name),affiliate_tiers(name)&order=created_at.desc&limit=10000",headers:["affiliate_id","name","email","partner_type","status","affiliate_code","coupon_code","tier","created_at","approved_at"],row:x=>[x.id,x.profiles?.name,x.profiles?.email,x.partner_type,x.status,x.affiliate_code,x.coupon_code,x.affiliate_tiers?.name,x.created_at,x.approved_at]},
  clicks:{path:"/rest/v1/affiliate_clicks?select=affiliate_id,is_unique,destination_path,campaign,source,referrer_host,created_at&order=created_at.desc&limit=10000",headers:["affiliate_id","unique","landing_page","campaign","source","referrer_host","created_at"],row:x=>[x.affiliate_id,x.is_unique,x.destination_path,x.campaign,x.source,x.referrer_host,x.created_at]},
  orders:{path:"/rest/v1/orders?affiliate_id=not.is.null&select=order_number,affiliate_id,status,payment_status,currency,subtotal_minor,discount_minor,total_minor,affiliate_source,affiliate_attribution_method,created_at&order=created_at.desc&limit=10000",headers:["order_reference","affiliate_id","order_status","payment_status","currency","subtotal_minor","discount_minor","total_minor","source","attribution_method","created_at"],row:x=>Object.values(x)},
  commissions:{path:"/rest/v1/affiliate_commissions?select=id,affiliate_id,order_id,commissionable_minor,commission_type,commission_value,commission_minor,currency,status,referral_source,campaign,risk,created_at&order=created_at.desc&limit=10000",headers:["commission_id","affiliate_id","order_id","basis_minor","type","value","amount_minor","currency","status","source","campaign","risk","created_at"],row:x=>Object.values(x)},
  payouts:{path:"/rest/v1/affiliate_payouts?select=id,affiliate_id,amount_minor,currency,status,payout_method,transaction_reference,requested_at,paid_at&order=requested_at.desc&limit=10000",headers:["payout_id","affiliate_id","amount_minor","currency","status","method","transaction_reference","requested_at","paid_at"],row:x=>Object.values(x)},
  leads:{path:"/rest/v1/affiliate_business_leads?select=id,affiliate_id,company_name,estimated_quantity,status,protection_expires_at,lead_source,created_at&order=created_at.desc&limit=10000",headers:["lead_id","affiliate_id","company","quantity","status","protection_expires_at","source","created_at"],row:x=>Object.values(x)},
  fraud:{path:"/rest/v1/affiliate_fraud_flags?select=id,affiliate_id,order_id,risk,reason_code,resolved_at,decision_reason,created_at&order=created_at.desc&limit=10000",headers:["flag_id","affiliate_id","order_id","risk","reason_code","resolved_at","decision_reason","created_at"],row:x=>Object.values(x)},
  campaigns:{path:"/rest/v1/affiliate_campaigns?select=id,affiliate_id,name,source,destination_path,active,created_at&order=created_at.desc&limit=10000",headers:["campaign_id","affiliate_id","name","source","destination","active","created_at"],row:x=>Object.values(x)},
};
export async function GET(request:Request){const actor=await requireAdmin();if(!actor)return Response.json({message:"Forbidden"},{status:403});try{const type=new URL(request.url).searchParams.get("type")||"affiliates";const report=reports[type];if(!report)return Response.json({message:"Unknown report."},{status:400});const{data}=await supabaseJson(report.path,{},true);const rows=[report.headers,...(data||[]).map(report.row)];return new Response(rows.map(row=>row.map(csv).join(",")).join("\r\n"),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="partner-${type}-${new Date().toISOString().slice(0,10)}.csv"`}})}catch(error){return safeError(error)}}
function csv(value:unknown){return`"${String(value??"").replace(/"/g,'""')}"`}
